# This file was generated by GoReleaser. DO NOT EDIT.
cask "eyebrow" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "6436e4e98d3b421782fbf472c50db228ab4b889075b0e5f0e09b1adea9483030"
      url "https://github.com/alexverify/eyebrow/releases/download/v#{version}/eyebrow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "32bff46adacb3ce06e268f8d5914af21d71ddb553faee7d375dd43b7ae3e307a"
      url "https://github.com/alexverify/eyebrow/releases/download/v#{version}/eyebrow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8fb0748d1455bf9a7eafd05066991bccc27c39b8c9cdf74b18a3fded2666b706"
      url "https://github.com/alexverify/eyebrow/releases/download/v#{version}/eyebrow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0dc59fffa0713e17ca7d55b0e7c4009aea1818d4b37ddff7749062c153216c03"
      url "https://github.com/alexverify/eyebrow/releases/download/v#{version}/eyebrow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "eyebrow"
  desc "Supply-chain integrity for AI coding tools"
  homepage "https://github.com/alexverify/eyebrow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eyebrow"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/eyebrow"]
    end
  end

  # No zap stanza required

end
