# This file was generated by GoReleaser. DO NOT EDIT.
cask "eyebrow" do
  version "0.5.4"

  on_macos do
    on_arm do
      sha256 "6451e5193fa75c1ff3afece5ba169076926181edca87f4f2865ea42674f9efec"
      url "https://github.com/alexverify/eyebrow/releases/download/v#{version}/eyebrow_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6c71da531a452ba9e8c49159dbf98b203faa73c3235caf31329aed749a0755fd"
      url "https://github.com/alexverify/eyebrow/releases/download/v#{version}/eyebrow_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "641cf84334164416405d113a2d33bd243ecfa93052ebef76cdcd8e1edd54b5aa"
      url "https://github.com/alexverify/eyebrow/releases/download/v#{version}/eyebrow_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d65e37322babaaba591abe9183eaec4a6536396acb98aa01a20ed4a731e2a2e6"
      url "https://github.com/alexverify/eyebrow/releases/download/v#{version}/eyebrow_#{version}_linux_amd64.tar.gz"
    end
  end

  name "eyebrow"
  desc "Supply-chain integrity for AI coding tools"
  homepage "https://github.com/alexverify/eyebrow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eyebrow"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/eyebrow"]
    end
  end

  # No zap stanza required
end
