# This file was generated by GoReleaser. DO NOT EDIT.
cask "eyebrow" do
  version "0.4.6"

  on_macos do
    on_arm do
      sha256 "41de8663b749ea52b8e9537aa270c3a20ec8e699e0c772f8dedd184595c694cc"
      url "https://github.com/alexverify/eyebrow/releases/download/v#{version}/eyebrow_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f4c9f3c785571ea01c334a63dfb04a62ddc36bb2a25e113df4e5f28a1e4a91b7"
      url "https://github.com/alexverify/eyebrow/releases/download/v#{version}/eyebrow_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "637a3c2422917156bd33fec97dcf208e2d9065a4d082af72fe11a42b82d9d8e6"
      url "https://github.com/alexverify/eyebrow/releases/download/v#{version}/eyebrow_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ac2e8c2c13464596b93413a5f63c9bd62729cee526ef242f7709020eb01d9b06"
      url "https://github.com/alexverify/eyebrow/releases/download/v#{version}/eyebrow_#{version}_linux_amd64.tar.gz"
    end
  end

  name "eyebrow"
  desc "Supply-chain integrity for AI coding tools"
  homepage "https://github.com/alexverify/eyebrow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eyebrow"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/eyebrow"]
    end
  end

  # No zap stanza required
end
